/* Source of truth: planning spreadsheet
   docs.google.com/spreadsheets/d/1AF7F3EAMm5um7JkE-A1ANgWMC3b-JPOPuNmY-1jSWg0
   Rows are transcribed verbatim, INCLUDING rows with shownOnUI 'N' — those are
   kept for reference and filtered out at render time (see resources-data.js).
   Columns: A Section | B Tag | C Order | D Audience | E Shown on UI |
            F Document Name | G Short Description | H Media Type | I Internal Link */
(function () {
  const R = (section, tag, order, audience, shown, name, desc, media, link) =>
    ({ section, tag, order, audience, shown, name, desc, media, link });

  window.RES_ROWS = [
    R('Introduction', '', 1, 'Members', 'Y', 'Membership Agreement',
      'The agreement you sign on joining. Countersigned copies are held by the E8 team.',
      'Document', 'https://docs.google.com/document/d/1j8isffgAU9xbAC4wWNyTh-Xj-xRSp_ca/edit?usp=sharing'),
    R('Introduction', '', 2, 'Members', 'Y', 'New Member Orientation - Nov 2025',
      'Recorded orientation session: the portal, the pipeline, and where new members plug in.',
      'Video', 'https://youtu.be/UO2oNKpJNoM'),
    R('Introduction', '', 3, 'Members', 'Y', 'Member Handbook',
      'How E8 works: membership classes, commitments, meeting cadence and the investment process end to end',
      'Document', 'https://docs.google.com/document/d/1A_mGHF6MqqrTEkGIIt-ljPqVmk3akVaS/edit?usp=sharing'),

    R("You're meeting: Entrepreneurs", 'Sourcing', 1, 'Members', 'N', 'How to refer a company to E8',
      'One page on what makes a good referral and what the company will be asked for.',
      'Document', 'https://docs.google.com/document/d/1YK8i7t9w-BrCxDfOnyx_znpCewcTrM5RxbvdeKRP6fk/edit?usp=sharing'),
    R("You're meeting: Entrepreneurs", 'Sourcing', 2, 'Members', 'Y', 'E8 Slide Deck (Entrepreneurs)',
      'The founder-facing story: what E8 funds, how the pipeline runs, what to expect after applying. Use when meeting entrepreneurs.',
      'Slides', 'https://docs.google.com/presentation/d/1Yv8zlvUemssA5Zz572oiidYfaP3dU40ZSKOITHbV6S8/edit?usp=sharing'),
    R("You're meeting: Entrepreneurs", 'Sourcing', 3, 'Members', 'Y', 'Refer a Company',
      'Submit a company lead. Takes two minutes; the screening team picks it up from there.',
      'Portal link', 'https://app.e8angels.com/forms/company-leads'),
    R("You're meeting: Partners", 'Sourcing', 4, 'Members', 'N', 'How to refer a partner to E8',
      '', '', ''),
    R("You're meeting: Partners", 'Sourcing', 5, 'Members', 'N', 'E8 Slide Deck (Partners)',
      'Use when meeting partners', '', ''),
    R("You're meeting: Sponsors etc?", 'Sourcing', 6, 'Members', 'N',
      "Connect them with the E8 team directly - how to talk about E8, what we're looking for, types of things they can sponsor.",
      '', '', ''),

    R('Pipeline', 'Overview', 1, 'All', 'Y', 'E8 Pipeline Handbook 2026 - 27',
      'The whole pipeline in one document: stages, roles, decision gates and timelines.',
      'Document', 'https://docs.google.com/document/d/1rWxXNX0d8RUUyzEBJspzUVEQsq0CE7XU/edit?usp=sharing'),
    R('Pipeline', 'Screening', 2, 'Members', 'Y', 'Rating Guide for Screeners',
      'What each score on the rating scale means, so screeners rate consistently.',
      'Document', 'https://docs.google.com/document/d/1OWbar9xW4cjpoPHA0FIAnMsiApowQS1V/edit?usp=sharing'),
    R('Pipeline', 'Pitch', 3, 'N/a', 'Y', 'E8 Pitch Preparation Guidance',
      'For Guides preparing a company to pitch: format, timing and the questions to expect.',
      'Document', 'https://docs.google.com/document/d/1xxUeaD5oqqPeFwD9S8cvsTpaMlaXWOoOj580oTPwTYs/edit?tab=t.0'),
    R('Pipeline', 'Follow-Up', 4, 'All', 'Y', 'E8 Follow-Up Meeting Guidance 2023-24',
      'How to run the follow-up meeting after a pitch, and what to record afterwards.',
      'Document', 'https://docs.google.com/document/d/1AvTAxPB2nW3Vlg2ckHdnzx1lykuGsDp3/edit?usp=sharing'),
    R('Pipeline', 'Follow-Up', 5, 'All', 'Y', 'Follow-Up Call - Slide Deck',
      'Template deck for the follow-up call. Duplicate it per company.',
      'Slides', 'https://docs.google.com/presentation/d/159DTRQYywQ0CRpikuEJKNh9tTFW89myM7LF8RbHCHW4/edit?usp=sharing'),
    R('Pipeline', '', null, 'Members', '', 'Diligence Talk - Dec 2024',
      'Recorded session on running due diligence well.', '', ''),
    R('Pipeline', 'Diligence', 6, 'All', 'Y', 'E8 Diligence Guidance',
      'What diligence covers at E8, how teams divide the work, and the standard of evidence expected.',
      'Document', 'https://docs.google.com/document/d/18RxRUC-EqCCzBLTX8veKkCsaExBHjjd5rigXc9bPhTs/edit?usp=sharing'),
    R('Pipeline', 'Diligence', 7, 'All', 'Y', 'Diligence Training',
      '', 'Video', 'https://youtu.be/6ETC73ylguI'),
    R('Pipeline', 'Diligence', 8, 'All', 'Y', 'Diligence Assistant FAQs',
      '', 'Document', 'https://docs.google.com/document/d/1m-i4a_ULwCiWmTwvIsvBBUYtVnBm8SxLeclSQtSp4y8/edit?usp=sharing'),
    R('Pipeline', 'Diligence', 9, 'All', 'N', 'Diligence Kick Off Meeting (Slide Deck)',
      'Deck for the kick-off: scope, workstreams and owners.',
      'Slides', 'https://docs.google.com/presentation/d/1dkIAQ3vpKn9B5MoM08R5A_CScL-SHVCqEnWxnudYPww/edit?usp=sharing'),
    R('Pipeline', 'Diligence', 10, 'All', 'Y', 'Diligence Weekly Calls (Slide Deck)',
      '', 'Slides', ''),
    R('Pipeline', 'Diligence', 11, 'All', 'Y', 'E8 Diligence Wrap Conversation (Slide Deck)',
      'Template for the wrap conversation: findings, risks and the recommendation to members.',
      'Slides', 'https://docs.google.com/presentation/d/1fd0LWm4cyt8Vua-bkmE2qYV9YaM0nD6QPnwNwI2Q0uM/edit?usp=sharing'),
    R('Pipeline', 'Diligence', 12, 'All', 'Y', 'Diligence Status Report for Member Meetings',
      'The standing format for reporting diligence progress at a member meeting.',
      'Slides', 'https://docs.google.com/presentation/d/16weMR58UfqdP2v842i2KjWImqYms3VPc3taprd9Ag-g/edit?usp=sharing'),

    R('Policy', 'Pipeline', 1, 'All', 'Y', 'AI Policy',
      'What members and Fellows may and may not put into AI tools when handling company material.',
      'Document', 'https://docs.google.com/document/d/1YSns_g_elWLjicvUZ-N21fHmDCzh4lbC9_yxisucI_U/edit?tab=t.fgw5uek54ab0'),
    R('Policy', 'Investment', 2, 'Members', 'Y', 'SPV Policy',
      'When an SPV is used, who may participate and how it is administered.',
      'Document', 'https://docs.google.com/document/d/1QedXiKkqAG-RCIoDkmitfDytWRbK_1xj2HXsTYYIkyU/edit?usp=sharing'),
    R('Policy', 'Investment', 3, 'Members', 'Y', 'Valuation Policy',
      'How E8 arrives at a valuation and the methodology members should assume.',
      'Document', 'https://docs.google.com/document/d/1-8TTIQES__I1P1wJb8tY2ZI047M1Dhvo/edit?usp=sharing'),
    R('Policy', 'Investment', 4, 'Members', 'Y', 'Data & Governance Policy',
      'Handling of company data, confidentiality and governance obligations.',
      'Document', 'https://docs.google.com/document/d/1QT6Ky01oGAMHGa_NX2uNiwiiCUSrOnbxsdp2dx6_3dU/edit?usp=sharing'),

    R('Fellows', '', 1, 'Fellows', 'Y', 'Fellows Handbook',
      'What the Fellowship involves: expectations, cadence and how Fellows join diligence teams.',
      'Document', 'https://docs.google.com/document/d/1Zlfw0i6bhBoy8v9YkvFU0-koJvBtVpEc/edit?usp=sharing'),
    R('Fellows', '', 2, 'Fellows', 'Y', 'E8 Fellows Orientation - Sep 2026',
      '', 'Slides', 'https://docs.google.com/presentation/d/1G9vmXg7RU_ExJn-x9d9dL0mhKNlizx4R/edit?usp=sharing'),

    R('Decarbon8', 'March 2027', 1, 'Members', 'Y', 'Legal Doc for D8', '', 'Document', ''),
    R('Decarbon8', 'March 2027', 2, 'Members', 'Y', 'D8 2026 Climate Resilience Scope',
      'The theme scope for the cycle: what is in and out of scope.',
      'Document', 'https://docs.google.com/document/d/1B7ot1VLK9urnFsAnZ1UgU0hLr2fb3OVS/edit'),
    R('Decarbon8', 'March 2027', 3, 'Members', 'Y', 'D8 Orientation',
      'Orientation for the Decarbon8 screening committee.',
      'Slides', 'https://docs.google.com/presentation/d/176MkfKHvtCGBlGhteBevBmIVPzu3S0ofIds0KWGzK7g/edit?usp=sharing'),
    R('Decarbon8', 'March 2027', 4, 'Members', 'Y', 'D8 Orientation Training Video',
      'Recorded training to accompany the orientation deck.',
      'Video', 'https://www.youtube.com/watch?v=meU0qIPi-_M&feature=youtu.be'),
    R('Decarbon8', 'March 2027', 5, 'Members', 'Y', 'D8 Scoring Guide',
      'Decarbon8-specific rating information for applications.',
      'Document', 'https://docs.google.com/document/d/1fZOJoLp9AMgUub9Nq5zbTy9QRQbeAlQ3txN4GaZ9ts0/edit?tab=t.0'),
    R('Decarbon8', 'March 2027', null, 'Members', 'N', 'Anything else? Sponsorship / letters?',
      '', 'Document', 'https://docs.google.com/document/d/1B7ot1VLK9urnFsAnZ1UgU0hLr2fb3OVS/edit')
  ];
})();
